default: &default 
  adapter: postgresql 
  encoding: unicode 
  pool: 5 
  username: root 
  password: root 
  host: localhost 
  port: 5432

development: 
  <<: *default 
  database: app_search_book_development

test: 
  <<: *default 
  database: app_search_book_test

production: 
  <<: *default 
  database: app_search_book_production